version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/app
      RABBIT_URL: amqp://guest:guest@rabbitmq/

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  